export const testParams = {
  mainPageUrl: 'https://capital.com',
  countries: ['de'],
  languages: ['de'],
  roles: [
    'NotReg',
    // 'Auth',
    // 'UnAuth',
  ],
  licence: {
    au: 'ASIC',
    ae: 'SCB',
    de: 'CYSEC',
    gr: 'CYSEC',
    es: 'CYSEC',
    fr: 'CYSEC',
    it: 'CYSEC',
    hu: 'CYSEC',
    nl: 'CYSEC',
    pl: 'CYSEC',
    ro: 'CYSEC',
    tw: 'SCB',
    hk: 'SCB',
  },
};
