export const testCases = [
  {
    us_id: 'US_11.02.03_01',
    level: 1,
    testSection: 'education',
    testPart: 'commoditiesTrading',
    testContainer: 'mainBanner',
    testElement: 'btnStartTrading',
    description: '[Start Trading] button visibility',
  },
  {
    us_id: 'US_11.02.03_02',
    level: 1,
    testSection: 'education',
    testPart: 'commoditiesTrading',
    testContainer: 'mainBanner',
    testElement: 'btnTryDemo',
    description: '[Demo button] visibility',
  },
  {
    us_id: 'US_11.02.03_03',
    level: 1,
    testSection: 'education',
    testPart: 'commoditiesTrading',
    testContainer: 'contentBlock',
    testElement: 'btnStartTrading',
    description: '[Start Trading] visibility',
  },
  // {
  //   us_id: 'US_11.02.03_04',
  //   level: 1,
  //   testSection: 'education',
  //   testPart: 'commoditiesTrading',
  //   testContainer: 'WidgetMostTraded',
  //   testElement: 'btnTrade',
  //   description: '[Trade] visibility',
  // },
  // {
  //   us_id: 'US_11.02.03_05',
  //   level: 1,
  //   testSection: 'education',
  //   testPart: 'commoditiesTrading',
  //   testContainer: 'blockStepsTrading',
  //   testElement: 'btnCreateVerifyYourAccount',
  //   description: '[1. Create & verify your account] visibility',
  // },
  // {
  //   us_id: 'US_11.02.03_06',
  //   level: 1,
  //   testSection: 'education',
  //   testPart: 'commoditiesTrading',
  //   testContainer: '',
  //   testElement: '',
  //   description: '',
  // },
  // {
  //   us_id: 'US_11.02.03_07',
  //   level: 1,
  //   testSection: 'education',
  //   testPart: 'commoditiesTrading',
  //   testContainer: '',
  //   testElement: '',
  //   description: '',
  // },
  // {
  //   us_id: 'US_11.02.03_08',
  //   level: 1,
  //   testSection: 'education',
  //   testPart: 'commoditiesTrading',
  //   testContainer: '',
  //   testElement: '',
  //   description: '',
  // },
  // {
  //   us_id: 'US_11.02.03_09',
  //   level: 1,
  //   testSection: 'education',
  //   testPart: 'commoditiesTrading',
  //   testContainer: '',
  //   testElement: '',
  //   description: '',
  // },
  // {
  //   us_id: 'US_11.02.03_10',
  //   level: 1,
  //   testSection: 'education',
  //   testPart: 'commoditiesTrading',
  //   testContainer: '',
  //   testElement: '',
  //   description: '',
  // },
  // {
  //   us_id: 'US_11.02.03_11',
  //   level: 1,
  //   testSection: 'education',
  //   testPart: 'commoditiesTrading',
  //   testContainer: '',
  //   testElement: '',
  //   description: '',
  // },
  // {
  //   us_id: 'US_11.02.03_12',
  //   level: 1,
  //   testSection: 'education',
  //   testPart: 'commoditiesTrading',
  //   testContainer: '',
  //   testElement: '',
  //   description: '',
  // },
  // {
  //   us_id: 'US_11.02.03.01_01',
  //   level: 2,
  //   testSection: 'education',
  //   testPart: 'commoditiesTrading',
  //   testContainer: '',
  //   testElement: '',
  //   description: '',
  // },
  // {
  //   us_id: 'US_11.02.03.01_02',
  //   level: 2,
  //   testSection: 'education',
  //   testPart: 'commoditiesTrading',
  //   testContainer: '',
  //   testElement: '',
  //   description: '',
  // },
  // {
  //   us_id: 'US_11.02.03.01_03',
  //   level: 2,
  //   testSection: 'education',
  //   testPart: 'commoditiesTrading',
  //   testContainer: '',
  //   testElement: '',
  //   description: '',
  // },
];
